### ISSUE TITLE
To Design and Construct PaymentGateway model using Razorpay.

### ISSUE THREAD

**Issue by Prananjay04** [Prananjay04/Version1.0#1]
Students are going to pay fees using this model.
Step 1-> On clicking Pay button, the next activity should launch in which student has to enter his details.
Step 2-> The student is going to choose payment method via credit card/ debit card/online netbanking/UPI payment.
Step 3-> The student is going to enter the amount and captcha then going to click on next button.
step 4-> The student have to enter the cvc for debit card or should use UPI app for payment, if payment is successfull then student id, payment amount, date and time get going to returned and will automatically going to store in the database with status successful.
Step 5->  If in case due to network issue if payment is failed then also to store that exception with time and date with payment status failed.

Note -> The Student id is going to be Uniquie Key here.

**Comment by Rushikesh-Khode** [comment]
starting to work on the issue. we will need a testing API key for Razorpay and Firebase.

**Comment by Prananjay04** [comment]
I have send the API keys on your personal number, check it.

**Comment by Rushikesh-Khode** [comment]
got it

**Comment by Rushikesh-Khode** [comment]
solved this issue
