### ISSUE TITLE
Payment Successful Message Error.

### ISSUE THREAD

**Issue by Prananjay04** [Prananjay04/Version1.0#9]
![image](https://user-images.githubusercontent.com/78221502/148417304-3d739df5-e756-4b7b-9c96-3580354ec99b.png)

The isuue can be created in the following manner->
1 -> Open the app then enter the amount then after clicking on payment button.
2 -> Choose GPay as your payment method.
3-> After opening Gpay, if you came back on the home page i.e. on the page where you entered the amount to pay by not paying the 
       amount , you will see Payment Successfull Message, but actually your payment is not successful.
Hope you get the snapshot that i have uploaded with the comment.

**Comment by Rushikesh-Khode** [comment]
because it is the testing mode, not full mode its work is to just test API calls not make payment.

**Comment by Prananjay04** [comment]
ok I got it now.
